db:
  image: postgres
  environment:
    - POSTGRES_USER=supermarket
    - POSTGRES_PASSWORD=docker_supermarket
    - PGDATA=/var/lib/postgresql/data/pgdata
  env_file:
    - .env
  expose:
    - "5432:5432"
redis:
  image: redis
  expose:
    - "6379:6379"
web:
  build: .
  command: foreman start
  environment:
    - RAILS_ENV=test
    - REDIS_URL=redis://redis:6379/0/supermarket
  volumes:
    - .:/supermarket
  ports:
    - "3000:3000"
  links:
    - db
    - redis
