db:
  image: postgres
  environment:
    - POSTGRES_USER=supermarket
    - POSTGRES_PASSWORD=docker_supermarket
    - PGDATA=/var/lib/postgresql/data/pgdata
  env_file:
    - .env
  expose:
    - "5432:5432"
redis:
  image: redis
  expose:
    - "6379:6379"
web:
  image: leftathome/supermarket
  environment:
    - DB_HOST=db
    - DB_USERNAME=supermarket
    - DB_PASSWORD=docker_supermarket
    - RAILS_ENV=development
    - REDIS_URL=redis://redis:6379/0/supermarket
  volumes:
    - .:/supermarket
  ports:
    - "3000:3000"
  links:
    - db
    - redis
